version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis 
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=root
    volumes:
      - 'redis-data:/data_redis'
    ports:
      - "6379:6379"
    networks:
      - backend

  # just in dev
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redis-insight:/data_redis_insight
    networks:
      - backend


  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - backend

  kafka1:
    image: bitnami/kafka:latest
    container_name: kafka_broker1
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://:9092,PLAINTEXT_HOST://:29092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka_broker1:9092,PLAINTEXT_HOST://localhost:29092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=2
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    networks:
      - backend

  kafka2:
    image: bitnami/kafka:latest
    container_name: kafka_broker2
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_LISTENERS=PLAINTEXT://:9093,PLAINTEXT_HOST://:29093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka_broker2:9093,PLAINTEXT_HOST://localhost:29093
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=2
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    ports:
      - "9093:9093"
      - "29093:29093"
    depends_on:
      - zookeeper
    networks:
      - backend

networks:
  backend:
    driver: bridge
  external:
    driver: bridge

volumes:
  redis-insight:
  redis-data: